# Generated by Django 4.1.2 on 2022-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=200)),
            ],
        ),
    ]
